---
resources:
  - name: resource-tutorial
    type: git
    source:
      uri: https://github.com/nvasilev98/concourse-studying.git

  - name: resource-app
    type: git
    source:
      uri: https://username:password@github.tools.sap/CalcAcademy/i536947.git
      branch: itests

jobs:
  - name: job-test-app
    public: true
    plan:
      - get: resource-tutorial
      - get: resource-app
        trigger: true
      - task: web-app-tests
        file: resource-tutorial/task_run_tests.yml
